[build]
  command = "pnpm install --shamefully-hoist && pnpm build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "10.4.1"
  VITE_API_URL = "https://verifai-backend-owak.onrender.com"
  VITE_AUTH0_DOMAIN = "dev-ochinamhe.us.auth0.com"
  VITE_AUTH0_CLIENT_ID = "your-auth0-client-id"
  VITE_AUTH0_AUDIENCE = "https://verifaiapp.netlify.app"
