services:
  - type: web
    name: verifai-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
      - key: FLASK_ENV
        value: production
      - key: BACKEND_URL
        value: https://verifai-backend-owak.onrender.com
      - key: FRONTEND_URL
        value: https://verifaiapp.netlify.app
      - key: CORS_ORIGINS
        value: https://verifaiapp.netlify.app
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: verifaipostgres
          property: connectionString
    healthCheckPath: /api/health
